### ISSUE TITLE
As a user, I want to have a map, so I can keep track of my notes.

### ISSUE THREAD

**Issue by Ekhorn** [FHICT-S-Koen/info-map#30]
**Acceptance Criteria**
 - The user gets shown their map after login.
 - The map must show the user's notes (depends on #36).

**Test cases**
- [ ] TC01
Step 1 - User logs in 
Result: Their map shows a list of the user's notes.
- [x] TC02
Step 1 - User does not log in 
Result: Text gets shown stating: “Login to view your notes.”

**Tasks**
- [x] Setup notes-service discovery client.
- [x] Setup spring cloud gateway.
- [x] Add missing workflow files, secrets, and Heroku apps for the gateway and discovery server.
- [x] Create get map endpoint by user id.
- [x] Create post map endpoint. 
- [ ] Write unit & integration tests.
- [x] Add global error handling to map-service.
- [x] After login, call get user map endpoint, if the user doesn't have a map then call post map endpoint (depends on: #37).
- [x] Create get notes endpoint by map id.
- [x] Create after opening the map call to get the map's notes.
- [x] Show the notes within a list.
