### ISSUE TITLE
As a user, I want to be able to create notes, so I can keep track of them.

### ISSUE THREAD

**Issue by Ekhorn** [FHICT-S-Koen/info-map#36]
**Acceptance Criteria**
- The user must be able to add notes as text, but only when they're logged in and have a map. (depends on #30)

**Test cases**
- [ ] TC01
Step 1 - Input: any string containing at least 1 non whitespace character.
Result: Note added.
- [ ] TC02
Step 1 - Input: empty string 
Result: Error message shown stating "Name must not be empty."
- [ ] TC03
Step 1 - Input: any string containing only whitespace characters. 
Result: Error message shown stating "Name must not be empty."

**Tasks**
- [x] Create post note endpoint. 
- [ ] Write unit & integration tests.
- [ ] Create input which when pressing enter submits and creates a new note.
