### ISSUE TITLE
As a developer, I want a dark mode implementation of the UI, so I don't get blinded.

### ISSUE THREAD

**Issue by Ekhorn** [FHICT-S-Koen/info-map#43]
**Acceptance Criteria**
- The actor must be able to switch between, dark and light mode.
- The app must show the user's system preference when loading the page.
- FOUC must be prevented.
- Every component must have a proper light and dark mode version.
- The Definition Of Done must state a rule that every UI component must support the light- and dark mode themes.

**Test cases**

**Tasks**
- [x] Add set user preference based on OS on page load. 
- [x] Add theme switcher component.
- [x] Add dark mode properties to every visible component.
- [x] Add a new rule to Definition Of Done stating: “Every UI component must support the light- and dark mode themes”.
